import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Presto Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Corporation",
              "name": "Presto Group",
              "url": "https://www.prestogroup.com/",
              "logo": "https://www.prestogroup.com/prestogroup-white-logo.png",
              "sameAs": [
                "https://www.facebook.com/prestogroup",
                "https://twitter.com/PrestoGroup",
                "https://www.linkedin.com/company/prestogroup/",
                "https://www.youtube.com/user/GroupPresto"
              ]
            })
          }}
        />
        <script
          async
          defer
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(), event:'gtm.js'}); var f=d.getElementsByTagName(s)[0], j=d.createElement(s), dl=l!='dataLayer'?'&l='+l:''; j.async=true; j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl; f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-KFWMTCZ');`,
          }}
        />
        <meta
          name="google-site-verification"
          content="--sjkT41wxYio7btn7tYffHVL2ukFd7nV0YpMFnRemU"
        />
        <meta
          name="facebook-domain-verification"
          content="nqw3qf9kawd655o26cvvi0pksbck19"
        />
        <link rel="icon" href="/favicon.png" />
        <script
          async
          defer
          type="text/javascript"
          src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
        />
        <script
          async
          defer
          src="https://www.googletagmanager.com/gtag/js?id=G-9ZTZJYGL44"
        ></script>
        <script
          async
          defer
          dangerouslySetInnerHTML={{
            __html: `window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-9ZTZJYGL44');`,
          }}
        />
        {/* <script
          async
          defer
          dangerouslySetInnerHTML={{
            __html: `window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
              d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
                _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
              $.src="//v2.zopim.com/?1ek5XPVjRxqvCzWD23xAzdWWZ04Rur4S";z.t=+new Date;$.
              type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");`,
          }}
        /> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />

      </body>
    </html>
  );
}
